id: I73342A2F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:21:54+00:00'
last_modified: '2022-06-08T11:44:29.127236+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4055
  title: རིག་འདུས་གསང་སྒྲུབ་རྡོ་རྗེའི་རྒྱ་ཅན་ལས་ལས་བྱང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4601':
      image_group_id: I3CN8470
      title: ''
      total_pages: 148
      order: 1
      base_file: 4601.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
