id: P009538
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4055
  title: རིག་འདུས་གསང་སྒྲུབ་རྡོ་རྗེའི་རྒྱ་ཅན་ལས་ལས་བྱང་།
  author: ''
  volumes:
    e3a03a6d065d4355a34301a7280832f9:
      image_group_id: I3CN8470
      title: ''
      volume_number: 1
      total_pages: 148
