id: P009538
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:37:03.985595
source_metadata:
  id: bdr:W3CN4055
  title: རིག་འདུས་གསང་སྒྲུབ་རྡོ་རྗེའི་རྒྱ་ཅན་ལས་ལས་བྱང་།
  author: ''
  volumes:
    e3a03a6d065d4355a34301a7280832f9:
      image_group_id: I3CN8470
      title: ''
      volume_number: 1
      total_pages: 148
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
